namespace kebormed.grpcservice.Models
{
    public class UserOrganization
    {
        public int Id { get; set; }  // This should be auto-generated by the database
        public int UserId { get; set; }
        public int OrganizationId { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime? DeletedAt { get; set; }

        public  bool IsAssociate { get; set; }
        public bool? IsDeleted { get; set; }

        //public User? User { get; set; }
        //public Organization? Organization { get; set; }
    }
}
